version: "3.3"

services: 
  app:
    build: .
    image: uriellabs/flaskr:1.0.0
    container_name: flaskr
    command: waitress-serve --call 'flaskr:create_app'
    ports: 
      - 8080:8080
    volumes: 
      - ./src:/app
